### ISSUE TITLE
Publish in the Chrome Webstore

### ISSUE THREAD

**Issue by bertocq** [o2dazone/StravaKudos#1]
Firstly **thank you** for creating and publishing this repo 💯 👏 ‼️  I really like this extension and  use it on a daily basis (following tons of other people sometimes consumes a lot of time clicking kudos).

The problem is: Every time I restart the browser (2-3 times a day) I get the annoying popup message "disable developer mode extensions" on the top right corner:

![screen shot 2017-03-05 at 14 31 43](https://cloud.githubusercontent.com/assets/983242/23587641/2021d160-01b1-11e7-984f-50898f6b7d4e.jpg)

I've tried to disable it but Googling only led me to patches for Chrome on Win (I'm on Mac), or making the extension click on the "Cancel" button somehow. But I think the best option is to just publish the extension. Also couldn't find any with same feature already published on the Chrome Webstore.

I know I'm asking you to do some work (that I think only you can do, let me know if I could help), so I understand if you don't see any value on it... but I'm just writing this because you may think that no-one cares/uses this. Well you've got a fan willing to help here :) Thanks again.

**Comment by o2dazone** [comment]
Hopefully this eases some of the pain of having to click Cancel a couple times a day

https://chrome.google.com/webstore/detail/strava-kudos/fmgpfcolhjopnnbklpambicfacbbhbac

And thanks for using this extension!
