### ISSUE TITLE
Auto-Kudos button not showing on club's recent activity page

### ISSUE THREAD

**Issue by yizeng** [o2dazone/StravaKudos#11]
Only happens at the latest Chrome Canary (Windows). Works fine in Chrome Stable .

Chrom Stable `Chrome Stable `Version 61.0.3163.100 (Official Build) (64-bit)`
- Dashboard :+1:
- Club's recent activities page  :+1:

Chrome Canary `Version 64.0.3266.0 (Official Build) canary (64-bit)`
- Dashboard :+1:
- Club's recent activities page  :-1:

No console errors seen.

**Comment by o2dazone** [comment]
Thanks @yizeng - confirmed this bug, I'll try to root it out. Appreciate the thorough description

**Comment by o2dazone** [comment]
Looks as though Google has [changed some functionality to extension styles](https://bugs.chromium.org/p/chromium/issues/detail?id=632009&desc=2). I've published a new version to the store which should appear in an hour or so. When this publishes, let me know if it works, and feel free to close the issue if it does

**Comment by yizeng** [comment]
@o2dazone It seems to be the same for me. Anything I can do to tell if I'm using the new version?

**Comment by o2dazone** [comment]
If you go to the [StravaKudos Chrome Webstore](https://chrome.google.com/webstore/detail/strava-kudos/fmgpfcolhjopnnbklpambicfacbbhbac) page, you should see a version published at the bottom of the popup window. Latest is 0.6, which contains the fix.

I also noticed Canary will suppress console log errors and display them in the Extensions page under that specific extension. If you are up to date, and you still don't see the button, perhaps copy paste the "Error" field under StravaKudos on the extensions page.

**Comment by csenior1** [comment]
I tried to load the 0.6 package and get the following error:

Could not load javascript "..index.js" for content script.

[image: Inline image 1]

**Comment by o2dazone** [comment]
I see this too, my apologies. I'll have a fix up shortly

**Comment by o2dazone** [comment]
Fix should be published in the store in the next hour. @csenior1 @yizeng please let me know if you have any issues with the latest (0.7)

**Comment by yizeng** [comment]
@o2dazone I don't have Chrome Canary anymore so it's been all good for me. 👍
