### ISSUE TITLE
Strava throttles kudos.

### ISSUE THREAD

**Issue by tomschlong** [o2dazone/StravaKudos#13]
The 500 ms delay seems too little. Strava server throws a 429 Too many requests. And blocks all post requests for 24 hours. Possibly IP ban. 
I tried 5000ms this seems to work. Maybe less would would too.

**Comment by o2dazone** [comment]
Thanks @tomschlong for the info! I personally haven't come across any throttling, so I appreciate you bringing this to my attention. When you said you tried 5000ms, did you run the extension unpacked with 5000ms and it worked for you? Would 2000ms work as well? If someone has 100+ kudos to automate, I feel like 5 seconds per kudo may take a while.

Also, if you're comfortable submitting a PR with a new interval time, I'd be glad to merge it.

**Comment by csenior1** [comment]
On the 24 hour computer browser block.. The way I have gotten around it to
kudo and comment via the mobile phone app. A few hours later the computer
browser block is lifted. Also Strava support has emailed me, that they only
allow 100 kudo limit every 10 minutes. I hope this helps.

**Comment by tomschlong** [comment]
@o2dazone I tested the extension unpacked with 1000ms now. This works fine for me. I am new to github so I'll have to look into how to submit a PR. In any case the change in code is so very minor.

@csenior1 thanks for the info. I just tested over 100 Kudos at 1000ms in less than 10 minutes, and had no errors. So I cannot confirm the 100 kudo limit from Strava support.

**Comment by o2dazone** [comment]
Thanks again for the testing @tomschlong - I can make the code change 👍 
@csenior1 that's rather interesting...like @tomschlong I have not experienced any 10 minute throttles, but I've created an issue in case it does happen, I figure we could use a timestamp the usage of the butto, and alert users of the cap

**Comment by o2dazone** [comment]
Thanks @tomschlong [for the PR](https://github.com/o2dazone/StravaKudos/pull/15) - Closing this issue but feel free to ping me if we need to keep this discussion going
