### ISSUE TITLE
100 kudos per 10 minutes throttle

### ISSUE THREAD

**Issue by o2dazone** [o2dazone/StravaKudos#14]
[Based on a comment](https://github.com/o2dazone/StravaKudos/issues/13#issuecomment-356319221) by @csenior1 - Strava claims to be throttling Kudos to 100 per 10 minutes. We should look into allowing 100 kudos per 10 minutes so as not to get people locked out

**Comment by o2dazone** [comment]
https://github.com/o2dazone/StravaKudos/commit/fea8417c5f75f6bad7ffc8980472525fb543906e

**Comment by o2dazone** [comment]
When exceeding 100 Kudos

![2018-05-08 2](https://user-images.githubusercontent.com/1907517/39776170-ddb3fc62-52b4-11e8-8956-5da6cda25615.png)

**Comment by PeerHoffmann** [comment]
Ahh okay thanks for the hint. Yes seems that I'm blocked at the moment. Sorry.
