### ISSUE TITLE
hasn't been working

### ISSUE THREAD

**Issue by h3rb3r7** [o2dazone/StravaKudos#16]
can't autoKudo since yesterday

**Comment by bertocq** [comment]
🤔 works for me right now (I'm on Chrome Version 64.0.3282.140 (Official Build) (64-bit) macOS)

**Comment by tomschlong** [comment]
works for me too. Win7 Chrome Version 64.0.3282.140 (Official Build)
(64-Bit)

**Comment by o2dazone** [comment]
Hey @h3rb3r7 

Working for me on MacOS
- Version 63.0.3239.132 (Official Build) (64-bit)
- Version 64.0.3282.140 (Official Build) (64-bit)

Can you give me some information as to what you're seeing (or not seeing)? Does a button display? Does a button display but clicking it does nothing? Do you see anything in the Javascript console?

**Comment by o2dazone** [comment]
Closing due to lack of information, and cannot validate
