### ISSUE TITLE
Kudos button does not work for next 40, 60, 80 activites

### ISSUE THREAD

**Issue by allisonwong** [o2dazone/StravaKudos#19]
The kudos button does not work once you scroll down the page to load the next 40, 60, 80, etc. activities.  The Kudos button appears but clicking it does not result in any kudos given.

**Comment by o2dazone** [comment]
You might've been throttled by Strava. Does clicking "Kudos" on an activity do anything? If not, you might've given too many Kudos in one go.

**Comment by allisonwong** [comment]
Yes, if I manually click on Kudos the Kudos is given.

**Comment by o2dazone** [comment]
Replicated. I assume this happens after you've clicked the button once, scrolling down loads more and clicking the button a second time does nothing?

**Comment by o2dazone** [comment]
Published version 0.11 to the store but it may take an hour or so for it to appear. Let me know if this works once it's updated.

**Comment by allisonwong** [comment]
It's working now, thanks so much for fixing!
