### ISSUE TITLE
Plugin doesn't work anymore

### ISSUE THREAD

**Issue by PeerHoffmann** [o2dazone/StravaKudos#21]
The plugin doesn't work anymore. Perhaps some changes from strava?

**Comment by o2dazone** [comment]
Hey @PeerHoffmann,

Just tested the extension in the latest stable Google Chrome, and the nightly Google Chrome Canary (77.0.3835.0 at the time of writing this), and it's working fine for me. Can you give me some more details?

- Does the button show up?
- If it does, when you click it, does nothing happen?
- Does it show you "Give X Kudos" in the button text?


I suspect you were throttled, which is a limitation Strava imposes to prevent too many kudos at a given time.

Related tickets: 

https://github.com/o2dazone/StravaKudos/issues/14
https://github.com/o2dazone/StravaKudos/issues/13

If you're comfortable with it, you can check the Network tab to determine if a throttling is happening. If it is, you should see requests to Kudos coming in as `429 Too many requests` (unless Strava has changed their API recently).

If you still can't "Give Kudos" by clicking the button manually, chances are you are throttled. I'm not sure how long the ban is (#13 says it can be up to 24 hours, but mobile application still works)

**Comment by PeerHoffmann** [comment]
Ahh okay thanks for the hint. Yes seems that I'm blocked at the moment. Sorry for the ticket
