### ISSUE TITLE
Download from Github for developer Install

### ISSUE THREAD

**Issue by ewanfletcher** [o2dazone/StravaKudos#22]
Would it be possible to provide a download from here that allows this extension to be loaded in Chrome manually via the developers option?

**Comment by o2dazone** [comment]
Hey @ewanfletcher 

You can use the “Clone or Download” link on this projects home page. 

![](https://github-images.s3.amazonaws.com/enterprise/2.21/assets/images/help/repository/clone-repo-clone-url-button.png)

There is a “Download ZIP” which allows you to side load the extension

**Comment by ewanfletcher** [comment]
I did try that, but it was throwing up errors .... I'll give it another try again.

Thanks for your reply

**Comment by o2dazone** [comment]
Hey @ewanfletcher,

Apologies, it was a late night for me. I've now included the `index.js` file necessary for making this extension sideloadable.
Once you've downloaded the ZIP file, you can navigate to the `/chrome-extesion/` folder on `chrome://extensions/` and sideload it there. Let me know if you run into any issues

**Comment by ewanfletcher** [comment]
No hassle at all ... I found the files and moved them about until i got them to work!
Cheers for the help.
