### ISSUE TITLE
Strava's UI is being A/B tested

### ISSUE THREAD

**Issue by o2dazone** [o2dazone/StravaKudos#29]
# Ignore this thread if StravaKudos is currently working for you

Strava is currently AB testing their web UI experience. I've made updates to StravaKudos to support the new experience, but some folks are still on the old web UI. I've since bundled up the old version and cut a release, but going forward, I will only be supporting their new UI, as I have no way of testing the old experience.

If the current StravaKudos extension from the Chrome Web Store does not work for you, try these steps

# 

[These instructions are taken from Google Chrome's developer docs](https://developer.chrome.com/docs/extensions/mv3/getstarted/#manifest)

- Download the old StravaKudos extension https://github.com/o2dazone/StravaKudos/releases/tag/v0.11 
  - Unzip the StravaKudos directory to somewhere where it wont get deleted 
- Open the Extension Management page by navigating to `chrome://extensions`.
  - Alternatively, open this page by clicking on the Extensions menu button and selecting **Manage Extensions** at the bottom of the menu.
  - Alternatively, open this page by clicking on the Chrome menu, hovering over **More Tools** then selecting **Extensions**
- Enable Developer Mode by clicking the toggle switch next to **Developer mode**.
- Click the **Load unpacked** button and select the extension directory.

![image](https://user-images.githubusercontent.com/1907517/127931926-1d132e6e-5802-4d22-abc6-039f14218246.png)

#

Again, this is only for users where the current StravaKudos extension does not work for them.

**Comment by creid0611** [comment]
Thanks for all of your hard work on this.
Sideloading the old version work a treat and my Kudos button is back.
Kudos to you for working it out.

**Comment by firozzer** [comment]
You sir get my utmost respect for the extreme dedication & good work you're doing. God bless!

**Comment by o2dazone** [comment]
This is no longer being a/b tested
