### ISSUE TITLE
Auto-Kudos everyone

### ISSUE THREAD

**Issue by thiswebhostinguk** [o2dazone/StravaKudos#6]
I don't want to have to follow everyone in my club but would still like to auto-kudos them. Is this possible?

**Comment by o2dazone** [comment]
Uploaded a new version of the Extension to the Chrome Webstore, should be fixed soon. Relevant commit https://github.com/o2dazone/StravaKudos/commit/424ccf905eb7810f00a8f7e8b1029660f401cb74
