### ISSUE TITLE
Kudos for Club Dashboard

### ISSUE THREAD

**Issue by csenior1** [o2dazone/StravaKudos#7]
The button works great on the main dashboard but when I open a club dashboard it does not work. Would it be possible to add code so that it works on any club dashboard?

https://www.strava.com/dashboard?club_id=XXXX&feed_type=club

Thank you!

**Comment by o2dazone** [comment]
Uploadd a new version of the Extension to the Chrome Webstore, should be fixed soon. Relevant commit https://github.com/o2dazone/StravaKudos/commit/424ccf905eb7810f00a8f7e8b1029660f401cb74
