### ISSUE TITLE
Pop up not showing

### ISSUE THREAD

**Issue by allisonwong** [o2dazone/StravaKudos#9]
After one day of doing fine/great, the pop up does not show in the "dashboard" anymore (so not able to give kudos via ext). I enabled and disabled the extension and that did not work either.

**Comment by o2dazone** [comment]
Thanks @allisonwong - I can duplicate this problem, I'll get a fix out asap

**Comment by o2dazone** [comment]
Fix pushed to chrome webstore https://github.com/o2dazone/StravaKudos/commit/1369d90252c61d6a6da48cb9ed1ca7a5cf07fd2f - should be up within the hour, thanks for the bug catching 👍
